// frontend/src/components/NavBar.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-white bg-white border-bottom px-4">
    <div class="container-fluid">
      <span class="navbar-brand fw-bold text-primary">Dashboard</span>
      <div class="d-flex align-items-center">
        <div class="dropdown">
          <button
            class="btn btn-link dropdown-toggle text-decoration-none text-dark"
            type="button"
            id="userDropdown"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ authStore.user?.full_name || 'User' }}
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
            <li><router-link class="dropdown-item" to="/dashboard/profile">Profile</router-link></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item text-danger" href="#" @click.prevent="logout">Logout</a></li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { useAuthStore } from '../store/auth';
import { useRouter } from 'vue-router';

const authStore = useAuthStore();
const router = useRouter();

const logout = () => {
  authStore.logout();
  router.push('/auth/login');
};
</script>

// frontend/src/components/Navbar.tsx
import { Link, useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';
import { Bus, User, LogOut } from 'lucide-react';

const Navbar = () => {
    const { user, isAuthenticated, logout } = useAuthStore();
    const navigate = useNavigate();

    const handleLogout = () => {
        logout();
        navigate('/');
    };

    return (
        <nav className="navbar navbar-expand-lg navbar-light bg-white shadow-sm border-bottom">
            <div className="container">
                <div className="d-flex justify-content-between align-items-center w-100">
                    <div className="d-flex align-items-center">
                        <Link to="/" className="d-flex align-items-center gap-2 text-decoration-none">
                            <Bus className="text-primary" size={32} />
                            <span className="h5 mb-0 font-weight-bold text-dark">BusTicket</span>
                        </Link>
                    </div>

                    <div className="d-flex align-items-center gap-3">
                        <Link to="/services" className="text-secondary text-decoration-none font-weight-medium">
                            Services
                        </Link>
                        {isAuthenticated ? (
                            <>
                                <div className="d-flex align-items-center gap-2 text-secondary">
                                    <User size={20} />
                                    <span className="d-none d-md-block font-weight-medium">{user?.full_name}</span>
                                </div>
                                <Link
                                    to="/my-tickets"
                                    className="text-secondary text-decoration-none font-weight-medium small"
                                >
                                    My Tickets
                                </Link>
                                <button
                                    onClick={handleLogout}
                                    className="btn btn-link text-danger text-decoration-none font-weight-medium small p-0 d-flex align-items-center gap-1"
                                >
                                    <LogOut size={16} />
                                    Logout
                                </button>
                            </>
                        ) : (
                            <>
                                <Link
                                    to="/login"
                                    className="text-secondary text-decoration-none font-weight-medium"
                                >
                                    Sign In
                                </Link>
                                <Link
                                    to="/register"
                                    className="btn btn-primary"
                                >
                                    Sign Up
                                </Link>
                            </>
                        )}
                    </div>
                </div>
            </div>
        </nav>
    );
};

export default Navbar;
